import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { chmodSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const installScriptPath = fileURLToPath(new URL("../scripts/install.sh", import.meta.url));
const repoDir = fileURLToPath(new URL("../", import.meta.url));
const installScript = readFileSync(installScriptPath, "utf8");
const doctorScript = readFileSync(new URL("../scripts/doctor.sh", import.meta.url), "utf8");

function createFakeOpenClaw(tempDir) {
  const fakeOpenClaw = join(tempDir, "openclaw");
  writeFileSync(
    fakeOpenClaw,
    `#!/bin/sh
if [ "$1" = "plugins" ] && [ "$2" = "info" ]; then printf '%s\n' 'Install path: ${repoDir}'; exit 0; fi
if [ "$1" = "plugins" ] && [ "$2" = "install" ]; then exit 0; fi
if [ "$1" = "gateway" ] && [ "$2" = "restart" ]; then exit 0; fi
if [ "$1" = "skills" ] && [ "$2" = "info" ]; then exit 1; fi
exit 0
`,
    "utf8",
  );
  chmodSync(fakeOpenClaw, 0o755);
  return fakeOpenClaw;
}

function runInstallerWithConfig(config, args = []) {
  const tempDir = mkdtempSync(join(tmpdir(), "openclaw-vocechat-install-test-"));
  const configPath = join(tempDir, "openclaw.json");
  const fakeOpenClaw = createFakeOpenClaw(tempDir);
  writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, "utf8");

  try {
    const output = execFileSync(
      "sh",
      [
        installScriptPath,
        "--config",
        configPath,
        "--base-url",
        "http://127.0.0.1:3000",
        "--api-key",
        "bot-api-key",
        "--skill-scope",
        "none",
        "--skip-restart",
        "--yes",
        ...args,
      ],
      {
        encoding: "utf8",
        env: {
          ...process.env,
          HOME: tempDir,
          OPENCLAW_BIN: fakeOpenClaw,
        },
      },
    );

    return {
      output,
      config: JSON.parse(readFileSync(configPath, "utf8")),
    };
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

test("install script leaves VoceChat webhook auth disabled unless explicitly provided", () => {
  assert.doesNotMatch(
    installScript,
    /WEBHOOK_API_KEY=\$\(random_secret\)/,
    "VoceChat native webhook cannot send x-api-key, so install.sh must not auto-generate webhookApiKey.",
  );
  assert.match(
    installScript,
    /VoceChat 原生 webhook 不会发送 x-api-key/,
    "The installer help text should document that direct VoceChat webhook callbacks cannot satisfy webhookApiKey.",
  );
  assert.doesNotMatch(
    installScript,
    /WEBHOOK_API_KEY=\$EXISTING_WEBHOOK_API_KEY/,
    "Re-running install.sh must not silently preserve an old webhookApiKey generated by earlier installer versions.",
  );
  assert.match(
    installScript,
    /delete vocechat\.webhookApiKey/,
    "Re-running install.sh without --webhook-api-key should remove stale webhookApiKey from channels.vocechat.",
  );
});

test("doctor accepts missing webhookApiKey for native VoceChat webhooks", () => {
  assert.match(
    doctorScript,
    /VoceChat webhookApiKey 未配置（适合 VoceChat 原生 webhook）/,
    "doctor.sh should report missing webhookApiKey as the normal native VoceChat webhook configuration.",
  );
  assert.doesNotMatch(
    doctorScript,
    /VoceChat 入站已启用，但 webhookApiKey 缺失/,
    "doctor.sh must not warn when native VoceChat webhook auth is intentionally disabled.",
  );
});

test("install script removes stale webhookApiKey by default", () => {
  const result = runInstallerWithConfig({
    channels: {
      vocechat: {
        enabled: true,
        baseUrl: "http://127.0.0.1:3000",
        apiKey: "old-bot-api-key",
        inboundEnabled: true,
        webhookPath: "/vocechat/webhook",
        webhookApiKey: "stale-webhook-key",
      },
    },
  });

  assert.equal(result.config.channels.vocechat.webhookApiKey, undefined);
  assert.match(result.output, /webhook 鉴权: 未配置（适合 VoceChat 原生 webhook）/);
});

test("install script writes webhookApiKey only when explicitly provided", () => {
  const result = runInstallerWithConfig(
    {
      channels: {
        vocechat: {
          enabled: true,
          baseUrl: "http://127.0.0.1:3000",
          apiKey: "old-bot-api-key",
          inboundEnabled: true,
          webhookPath: "/vocechat/webhook",
        },
      },
    },
    ["--webhook-api-key", "explicit-webhook-key"],
  );

  assert.equal(result.config.channels.vocechat.webhookApiKey, "explicit-webhook-key");
  assert.match(result.output, /webhook 鉴权头: x-api-key: explicit-webhook-key/);
});

test("install script fails early when config file is not writable", () => {
  const tempDir = mkdtempSync(join(tmpdir(), "openclaw-vocechat-install-ro-"));
  const configPath = join(tempDir, "openclaw.json");
  const fakeOpenClaw = createFakeOpenClaw(tempDir);
  writeFileSync(
    configPath,
    `${JSON.stringify({ channels: { vocechat: { enabled: true, baseUrl: "http://127.0.0.1:3000", apiKey: "old-bot-api-key" } } }, null, 2)}\n`,
    "utf8",
  );
  chmodSync(configPath, 0o400);

  try {
    assert.throws(
      () =>
        execFileSync(
          "sh",
          [
            installScriptPath,
            "--config",
            configPath,
            "--base-url",
            "http://127.0.0.1:3000",
            "--api-key",
            "bot-api-key",
            "--skill-scope",
            "none",
            "--skip-restart",
            "--yes",
          ],
          {
            encoding: "utf8",
            env: {
              ...process.env,
              HOME: tempDir,
              OPENCLAW_BIN: fakeOpenClaw,
            },
          },
        ),
      /配置文件不可写|permission denied/,
    );
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
});
